// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:notes/models/note_v1.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteV1Adapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NoteV1Adapter());
  }
}
